def format_supply_flow(amount, unit, location, activity_type, flow_object, unit, time, determining_flow, counter, supply_dict={}):
    """Return a list of RDF triples as Python for a supply ``Flow``.

    ``amount`` is a float.

    The following are strings **with URI prefixes already substituted**:

        * ``unit``
        * ``location``
        * ``activity_type``
        * ``unit``
        * ``flow_object``
        * ``time``

    ``determining_flow`` is a boolean indicating whether the flow is a determining flow.

    ``counter`` is an instance of ``collections.Counter`` used to count blank nodes.

    ``supply_dict`` is a dictionary that we keep to do lookups in the future. It has the form ``(activity_type_uri, location_uri): activity_uri``, where the ``activity_uri`` is generated by this function.

    """
    activity_uri = "brdfsu:{}".format(next(counter))
    flow_uri = "brdfsu:{}".format(next(counter))
    output = [{
        # Activity instance
        "@id" : activity_uri,
        "@type" : "bont:Activity",
        "bont:activityType" : activity_type,
        "bont:location": location,
        "bont:temporalExtent": time,
    }, {
        # Flow instance
        "@id": "brdfsu:{}".format(next(counter)),
        "@type" : "bont:Flow",
        "bont:outputOf": activity_uri,
        "om2:hasNumericalValue": amount,
        "bont:objectType" : flow_object,
        "om2:hasUnit" : "om2:" + unit
    }]
    if determining_flow:
        output[0]["bont:determiningFlow"] = flow_uri
        supply_dict[(activity_type, location)] = activity_uri
    return output, supply_dict


def format_domestic_use_flow(amount, unit, location, activity_type, flow_object, unit, time, counter, supply_dict):
    """Return a list of RDF triples as Python for a domestic use ``Flow``.

    ``amount`` is a float.

    The following are strings **with URI prefixes already substituted**:

        * ``unit``
        * ``location``
        * ``activity_type``
        * ``unit``
        * ``flow_object``
        * ``time``

    ``determining_flow`` is a boolean indicating whether the flow is a determining flow.

    ``counter`` is an instance of ``collections.Counter`` used to count blank nodes.

    ``supply_dict`` is generated by ``format_supply_flow``, and has the form ``(activity_type_uri, location_uri): activity_uri``

    """
    activity_uri = supply_dict[(activity_type, location)]
    flow_uri = "brdfsu:{}".format(next(counter))
    input_ = [{
        # Flow instance
        "@id": "brdfsu:{}".format(next(counter)),
        "@type" : "bont:Flow",
        "bont:inputOf": activity_uri,
        "om2:hasNumericalValue": amount,
        "bont:objectType" : flow_object,
        "om2:hasUnit" : "om2:" + unit
    }]
    return output
