package:
  name: bontofrom-dev
  version: {{ environ['VERSION'] }}

source:
  path: ..

build:
  noarch_python: True
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  script_env:
   - VERSION
   - CONDA_BLD_PATH

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - <other conda dependencies>

test:
  imports:
    - {{ name }}

about:
  home: <Github repo URL>
  license: BSD License
  summary: 'parse a table and create a BONsai onTOlogy from the table' 
license_family: BSD
